POST http://localhost:3003/infocontact
Content-Type: application/json

{
    "name":"Angel Guide",
    "subject":"Welcome address",
    "email":"lur129@gmail.com",
    "phone":"+49 123 45566",
    "text":"Working at alst"
}